// pantry-client/src/components/RefuelLogin.jsx
import React, { Component } from "react";
import {
    Section,
    Container,
    Columns,
    Form,
    Button
} from "react-bulma-components";

export default class Home extends Component {
    constructor(props) {
       super(props);
       this.state = {
           username: '',
           password: ''
       };
       this.securityService = this.props.securityService;
    }

    render() {
        return (
            <Section>
                <Container>
                    <Columns>
                        <Columns.Column
                            size="half"
                            offset="one-quarter"
                        >
                            <form>
                                <Form.Field>
                                    <Form.Label>Username</Form.Label>
                                    <Form.Control>
                                        <Form.Input
                                            color="refuel"
                                            value={this.state.username}
                                            type="text"
                                            onChange={(e) => {
                                                return this.setState({ username: e.target.value });
                                            }}
                                        />
                                    </Form.Control>
                                </Form.Field>
                                <Form.Field>
                                    <Form.Label>Password</Form.Label>
                                    <Form.Control>
                                        <Form.Input
                                            color="refuel"
                                            value={this.state.password}
                                            type="password"
                                            onChange={(e) => {
                                                return this.setState({ password: e.target.value });
                                            }}
                                        />
                                    </Form.Control>
                                </Form.Field>
                                <Form.Field>
                                    <Form.Control>
                                        <Button
                                            color="refuel"
                                            onChange={null}
                                            onClick={ (e) => {
                                                e.preventDefault();
                                                this.securityService.login(this.state.username, this.state.password)
                                            }}
                                        >
                                            Login
                                        </Button>
                                    </Form.Control>
                                </Form.Field>
                            </form>
                        </Columns.Column>
                    </Columns>
                </Container>
            </Section>
        );
    }
}

// pantry-client/src/components/RefuelLogin.vue
<template>
    <section class="section">
        <div class="container">
            <div class="columns">
                <div class="column">
                    <form>
                        <b-field label="Username">
                            <b-input v-model="username"></b-input>
                        </b-field>
                        <b-field label="Password">
                            <b-input type="password" v-model="password"></b-input>
                        </b-field>
                        <b-field>
                            <p class="control">
                                <b-button label="Login" type="is-refuel" @click="login" />
                            </p>
                        </b-field>
                    </form>
                </div>
            </div>
        </div>
    </section>
</template>

<script>
import { toast } from "bulma-toast"

export default {
    name: "RefuelLogin",
    inject: ['securityService'],
    data() {
        return {
            username: null,
            password: null,
        }
    },
    methods: {
        login: function() {
            this.securityService.login(this.username, this.password)
                .then(() => {
                    toast({
                        message: 'Login successful!',
                        type: 'is-success',
                        dismissible: true,
                        animate: { in: 'fadeIn', out: 'fadeOut' },
                    })
                }, (rej) => {
                    const errorMessage = `${rej.errors[0].field}: ${rej.errors[0].message[0]}`
                    toast({
                        message: errorMessage,
                        type: 'is-danger',
                        dismissible: true,
                        animate: { in: 'fadeIn', out: 'fadeOut' },
                    })  
                })
        }
    }
}
</script>
